apiVersion: postgresql.cnpg.io/v1
kind: Cluster
metadata:
  name: immich-postgres
  namespace: immich
spec:
  instances: 1

  storage:
    size: 20Gi
    storageClass: longhorn

  bootstrap:
    initdb:
      database: immich
      owner: immich
      secret:
        name: immich-db-user

