---
- name: Label selected Kubernetes nodes for Longhorn default disk creation
  hosts: localhost
  connection: local
  gather_facts: false
  become: false

  vars:
    kubeconfig_path: "{{ lookup('env', 'HOME') }}/.kube/homelab-config.yaml"
    longhorn_storage_label: "node.longhorn.io/create-default-disk=true"

  environment:
    KUBECONFIG: "{{ kubeconfig_path }}"

  tasks:
    - name: Check kubeconfig file exists
      ansible.builtin.stat:
        path: "{{ kubeconfig_path }}"
      register: kubeconfig_file

    - name: Fail if kubeconfig file is missing
      ansible.builtin.fail:
        msg: "Kubeconfig not found at {{ kubeconfig_path }}"
      when: not kubeconfig_file.stat.exists

    - name: Show nodes selected for Longhorn storage
      ansible.builtin.debug:
        msg: "{{ groups['longhorn_storage_nodes'] }}"

    - name: Label selected nodes for Longhorn default disk creation
      ansible.builtin.command: >
        kubectl label node {{ item }}
        {{ longhorn_storage_label }}
        --overwrite
      loop: "{{ groups['longhorn_storage_nodes'] }}"
      changed_when: "'not labeled' not in longhorn_label_result.stdout"
      register: longhorn_label_result

    - name: Show Longhorn node labels
      ansible.builtin.command: >
        kubectl get nodes
        -L node.longhorn.io/create-default-disk
      changed_when: false
      register: longhorn_node_labels

    - name: Print Longhorn node labels
      ansible.builtin.debug:
        var: longhorn_node_labels.stdout_lines