---
- hosts: all
  gather_facts: false
  tasks:
    - block:
        - name: Update all packages
          yum:
            name: '*'
            state: latest
          become: true

        - name: Ping the machine
          ping:

        - name: Ensure python 3 is installed
          yum:
            name: python3
            state: present
          become: true

        - name: Install Speedtest CLI repository
          shell: curl -s https://packagecloud.io/install/repositories/ookla/speedtest-cli/script.rpm.sh | sudo bash
          become: true

        - name: Ensure speedtest-cli is installed
          pip:
            name: speedtest-cli
            state: present

        - name: Run speedtest
          command: speedtest-cli --simple
          register: speedtest_output

        - name: Log speedtest results
          copy:
            content: "{{ speedtest_output.stdout }}"
            dest: "/var/log/speedtest.log"
          become: true