---
- hosts: all
  gather_facts: false
  tasks:
    - block:
        - name: Update all packages
          yum:
            name: '*'
            state: latest
          become: true

        - name: Ping the machine
          ping:

        - name: Ensure python 3 is installed
          yum:
            name: python3
            state: present
          become: true

        - name: Install Speedtest CLI repository
          shell: curl -s https://packagecloud.io/install/repositories/ookla/speedtest-cli/script.rpm.sh | sudo bash
          become: true

        - name: Ensure Speedtest is installed
          yum:
            name: speedtest
            state: present
          become: true

        - name: Run speedtest
          command: speedtest --accept-gdpr
          register: speedtest_output

        - name: Display speedtest results
          debug:
            msg: "{{ speedtest_output.stdout }}"