defaultSettings:
  createDefaultDiskLabeledNodes: true
  defaultReplicaCount: 2
  replicaSoftAntiAffinity: true
  storageOverProvisioningPercentage: 100
  storageMinimalAvailablePercentage: 10

persistence:
  defaultClass: true
  defaultClassReplicaCount: 2

ingress:
  enabled: true
  ingressClassName: nginx
  host: longhorn.janisberzins.xyz
  tls: true
  tlsSecret: longhorn-tls
  annotations:
    cert-manager.io/cluster-issuer: letsencrypt-prod
