defaultSettings:
  defaultDataPath: /var/lib/longhorn
  replicaSoftAntiAffinity: false
  storageOverProvisioningPercentage: 100
  storageMinimalAvailablePercentage: 15

persistence:
  defaultClass: true
  defaultClassReplicaCount: 2
  reclaimPolicy: Retain